name: Build Octopus APK

on:
  push:
    branches: [ main, master ] # Déclenche la compilation à chaque sauvegarde

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Recuperer le code
      uses: actions/checkout@v4 # Mis à jour en v4

    - name: Installer Java
      uses: actions/setup-java@v4 # Mis à jour en v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Installer Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Telecharger les modules
      run: flutter pub get

    - name: Compiler l'APK
      run: flutter build apk --release --no-tree-shake-icons

    - name: Rendre l'APK disponible
      uses: actions/upload-artifact@v4 # Corrigé en v4 pour résoudre ton erreur !
      with:
        name: Octopus-APK
        path: build/app/outputs/flutter-apk/app-release.apk
        
